# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notissu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticefiles',
            old_name='noticeId',
            new_name='notice_Id',
        ),
    ]
