# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notissu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticefiles',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
