# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notissu', '0002_auto_20170301_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='noticefiles',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
