# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notissu', '0002_auto_20170206_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticefiles',
            old_name='notice_Id',
            new_name='notice',
        ),
    ]
