# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notissu', '0002_auto_20170222_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='hash',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
